<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>org.drools.dotnet.examples</RootNamespace>
    <AssemblyName>drools.dotnet.examples</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="drools-3.0">
      <HintPath>..\lib\drools-3.0.dll</HintPath>
    </Reference>
    <Reference Include="IKVM.GNU.Classpath">
      <HintPath>..\lib\IKVM.GNU.Classpath.dll</HintPath>
    </Reference>
    <Reference Include="nunit.framework">
      <HintPath>..\lib\nunit.framework.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\drools.dotnet\drools.dotnet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="resources\**\*" />
    <EmbeddedResource Include="rules\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="benchmark\models\*.cs.b" />
  </ItemGroup>

</Project>